root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
full_bin = "export KGPZ_WATCH=false; ./tmp/main"
cmd = "go build -tags=\"dev\" -o ./tmp/main ."
delay = 400
exclude_dir = [
  "views/public",
  "views/node_modules",
  "views/transform",
  "tmp",
  "vendor",
  "testdata",
  "data_git",
  "cache_gnd",
  "cache_geonames",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "gohtml"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[proxy]
app_port = 8080
enabled = true
proxy_port = 8081

[screen]
clear_on_rebuild = true
keep_scroll = true
